// config.js
module.exports = {
  mongoUri: process.env.MONGODB_URI || 'mongodb://localhost:27017/smartlife',
  mongoDnsServers: process.env.MONGODB_DNS_SERVERS,
  lineUserId: process.env.LINE_USER_ID,
  lineAccessToken: process.env.LINE_ACCESS_TOKEN,
  weatherApiKey: process.env.WEATHER_API_KEY,
  publicBaseUrl: process.env.PUBLIC_BASE_URL || process.env.APPOINTMENTS_PANEL_URL,
  liffId: process.env.LIFF_ID,
  aiProvider: process.env.AI_PROVIDER || 'auto',
  aiFallbackProviders: process.env.AI_FALLBACK_PROVIDERS || 'gemini,groq,openrouter,huggingface,pollinations',
  aiModel: process.env.AI_MODEL,
  aiMaxHistory: Number(process.env.AI_MAX_HISTORY) || 12,
  geminiApiKey: process.env.GEMINI_API_KEY,
  geminiModel: process.env.GEMINI_MODEL || process.env.AI_MODEL || 'gemini-2.5-flash',
  groqApiKey: process.env.GROQ_API_KEY,
  groqModel: process.env.GROQ_MODEL || process.env.AI_MODEL || 'llama-3.1-8b-instant',
  openrouterApiKey: process.env.OPENROUTER_API_KEY,
  openrouterModel: process.env.OPENROUTER_MODEL || process.env.AI_MODEL || 'openrouter/free',
  huggingFaceToken: process.env.HF_TOKEN || process.env.HUGGINGFACE_API_KEY,
  huggingFaceModel: process.env.HF_MODEL || process.env.HUGGINGFACE_MODEL || process.env.AI_MODEL || 'deepseek-ai/DeepSeek-V3-0324',
  pollinationsApiKey: process.env.POLLINATIONS_API_KEY || process.env.POLLINATIONS_KEY,
  pollinationsTextModel: process.env.POLLINATIONS_TEXT_MODEL || process.env.POLLINATIONS_MODEL || process.env.AI_MODEL || 'openai',
  ollamaBaseUrl: process.env.OLLAMA_BASE_URL || 'http://localhost:11434',
  ollamaModel: process.env.OLLAMA_MODEL || process.env.AI_MODEL || 'qwen2.5:7b',
  paymentInstructions: process.env.PAYMENT_INSTRUCTIONS,
  paymentPromptPay: process.env.PAYMENT_PROMPTPAY,
  paymentBankAccount: process.env.PAYMENT_BANK_ACCOUNT,
  paymentQrUrl: process.env.PAYMENT_QR_URL
};
